### ISSUE TITLE
Screw holes, alignmemt pin holes, fan power pins, and overall pcb width do not match model 20F

### ISSUE THREAD

**Issue by SamBushman** [cyo-the-vile/FMT-ATX-TOWER#1]

**Comment by SamBushman** [comment]
![0528231347](https://github.com/cyo-the-vile/FMT-ATX-TOWER/assets/1577983/312840de-e95a-494e-ab4a-80458d1d1c9d)
Attached is a photo of 
![0528231850_HDR](https://github.com/cyo-the-vile/FMT-ATX-TOWER/assets/1577983/d8800710-6a7f-4970-99e3-9274f5a5a49d)
the board failing to align on one side and the fan power port being misaligned relative to the exhast fan frame

**Comment by SamBushman** [comment]
I'll hold onto my original power supply PCB. Lmk if it would be helpful to make it available

**Comment by cyo-the-vile** [comment]
This isnt true at all because the original card was based on a 20F I ripped
apart. Its been used on gen 2, 3 and 4 units. You might find a single hole
might not line up perfectly but Ive done 4 board revisions at this point
trying to line up holes. In recent install only 1 single hole was
problematic.

Use a 2.54mm header instead of recycling the original fan connector.  Check
the photos here.

https://townsworld.com/2021/05/08/fm-towns-tower-power-supply-assembly-guide/

**Comment by SamBushman** [comment]
I don't if maybe the Towns had multiple power supplies manufactured or something, but looking at one of the PCBs I had made, it is clearly wider than the original power supply board.
![0529230706_HDR](https://github.com/cyo-the-vile/FMT-ATX-TOWER/assets/1577983/bcf2e397-8d99-4597-9fd1-901d5eb62891)

Attached is a picture of the identification from the original power supply's PCB if that would help
![0529230707_HDR](https://github.com/cyo-the-vile/FMT-ATX-TOWER/assets/1577983/6d896ca7-d20a-493b-8c02-903691146402)

**Comment by cyo-the-vile** [comment]
Dude it doesnt matter; my board works.

**Comment by SamBushman** [comment]
Electricly it does, and its been great in that regard. I'm just trying to provide feedback from the experience I had putting it together to help improve the design.
